apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80        # Exposed port
      targetPort: 5000  # Port your Flask app listens on
  type: LoadBalancer  # Use NodePort or ClusterIP if you're testing locally (like with Minikube)
